[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
[project]
name = "schedulerx"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = ["python-dateutil>=2.8.2"]
